spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudshop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  testhaha
gril:
  name: Whaleson
  age: 20
